airquality<-datasets::airquality
head(airquality,5)
tail(airquality,3)
summary(airquality)
summary(airquality[ ,3])
summary(airquality$Temp)
par(mfrow=c(3,3),mar=c(2,5,2,1)
plot(airquality$Ozone)
plot(airquality$Ozone,airquality$Wind)
plot(airquality)
plot(airquality$Ozone,type='l',xlab='ozone concentration',ylab='no of instance',main='ozone levels in NY city',col='blue')
barplot(airquality$Solar.R,type='l',xlab='solar concentration',ylab='no of instances',main='solar levels',col='blue')
hist(airquality$Solar.R)
hist(airquality$Wind,xlab='wind concetration',ylab='no of instances',col='red')
boxplot(airquality)
boxplot(airquality[,1:4],main="multiple box plots")
